name: Checking Project
on:
  push:
    branches: -master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Yo Let's Installing Dependecy
        run: npm install

      - name: Let's Buld the Project
        run: npm run build

      - name: Let's Lint the Project
        run: npm run lint
        env:
          CI: true
